{
    "config": {
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_auth": "\u00c9rv\u00e9nytelen hiteles\u00edt\u00e9s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Jelsz\u00f3",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v"
                },
                "description": "Az IoTawatt eszk\u00f6z hiteles\u00edt\u00e9st ig\u00e9nyel. K\u00e9rj\u00fck, adja meg felhaszn\u00e1l\u00f3nev\u00e9t \u00e9s jelszav\u00e1t, majd kattintson a mehet gombra."
            },
            "user": {
                "data": {
                    "host": "Hoszt"
                },
                "data_description": {
                    "host": "Az IoTaWatt-eszk\u00f6z g\u00e9pneve vagy IP-c\u00edme."
                }
            }
        }
    }
}